### ISSUE TITLE
Can't add to Date

### ISSUE THREAD

**Issue by krlmlr** [rstats-db/hms#20]
https://github.com/rstats-db/hms/issues/18#issuecomment-224619267

```R
as.Date("2016-03-31") + hms(minutes = 1)
#> Warning: Incompatible methods ("+.Date", "Ops.hms") for "+"
#> [1] "2016-05-30"
```

**Comment by krlmlr** [comment]
Works in 30f6dfa35be8ebc9f4.

**Comment by edzer** [comment]
I think this should return a `POSIXct` datetime object, unless hms mod 24h is zero.
